var PerStreet = $("peraddstreet").val(); //20b
var NearbyLandmark = $("peraddlandmark").val(); //20c
var PerTaluk = $("peraddtaluk").val(); //20d
var PerCity = $("peraddcity").val(); //20e var District = $("perdistrictper").val(); //20f
var PerDist = $("perdistrictper").val(); //20g
var PerOtherDist = $("otherdistper").val(); //20g
var PerState = $("perstate").val(); //20g
var PerPinCode = $("perpincode").val(); //20h =

var Category = $("category").val(); //21 var SubCaste $("subcaste").val(); //21a =

var Dateof = $("doisubcaste").val(); //21b

var SclaimingRural = $("ruralreservationyes").val(); //22 DateofIssue = $("dateofissueofruralmedium").val(); //22a

varExServiceman = $("exservice-section").val(); //23 Armed Force = $("exarmed forcesyes").val(); //23a

var DateofJoining = $("dateofjoiningexser").val(); //23b Noc = $("dateofnocexser").val(); //23c

var ServiceRendered = $("ServiceRenderedexser").val(); //23d Discharge $("dateofdisexser").val(); //23e

var yearsof = $("dateofdisexser").val(); //23f

var DoorNo = $("peradddoor").val();     //20a
var Street = $("peraddstreet").val();    //20b
var NearbyLandmark = $("peraddarea").val(); //20c
var Taluk = $("peraddtaluk").val();   //20d
var City = $("peraddcity").val(); //20e
var District = $("perdistrictper").val(); //20f
var State = $("perstate").val(); //20g
var PinCode = $("perpincode").val(); //20h
var Category = $("category").val(); //21
var SubCaste = $("subcaste").val(); //21a
var Dateof = $("#doisubcaste").val(); //21b
var claimingRural = $("#ruralreservationyes").val(); //22
var DateofIssue = $("#dateofissueofruralmedium").val(); //22a
var ExServiceman = $("#exservice-section").val(); //23
var ArmedForce = $("#expresentlyServing").val();  //23a
var DateofJoining = $("#dateofjoiningexser").val(); //23b
var Noc = $("#dateofnocexser").val(); //23c
var ServiceRendered = $("#ServiceRenderedexser").val(); //23d
var Discharge = $("#dateofdisexser").val(); //23e
var yearsOf = $("#exyearsOfService").val(); //23f
var ExServiceman = $("#exServicemanChildyes").val(); //24
var RelationShip = $("#famrelation").val(); //24a
var Action = $("input[name='exServicemanfamded']:checked").val();   //24b
var Disabled = $("input[name='exServicemandis']:checked").val(); //24c
var Reservation = $("input[name='pdpreservation']:checked").val(); //25
var Certificate = $("#issueofpdpcer").val(); //25a
var MediumReservation = $("input[name='kanmediumreservation']:checked").val(); //26
var certificateforKannada = $("#kannadamedium").val(); //26a
var Transgender = $("input[name='transgenderreservation']:checked").val(); //27
var TransgenderReservation = $("#transgender-certificate-date").val(); //27a
var KalyanaKarnataka = $("input[name='kalyanakarnataka']:checked").val(); //28
var MentionYour = $("#kaldis").val(); //28a
var GovernmentEmployee = $("input[name='governmentemployee']:checked").val(); //29
var DateofJoining = $("#dojoi").val(); //29A
var Department = $("#subcaste").val(); //29B
var Years = $("#exyearsOfService").val(); //29C
var Month = $("#exMonthsOfService").val(); //29C
var Days = $("#exdaysOfService").val(); //29C
var DateofNoc = $("#dateofnocgovtdept").val(); //29d
var InServiceCandidate = $("input[name='inServicecandidate']:checked").val(); //30
var wingoftheKsp = $("#inServicewingname").val(); //30a
var wingoftheKsp1 = $("#inServicedate").val(); //30a
var InservicejoiningDate = $("#inServicejoiningdate").val(); //30b
var InservicejoiningRendered = $("#inServicerendered").val(); //30b
var YearsofserviceRendered = $("#inServicenumberyears").val(); //30c
var MonthsofserviceRendered = $("#inServiceMonths").val(); //30c
var DaysofserviceRendered = $("#inServiceDays").val(); //30c
var CriminalCases = $("input[name='criminalcasesinvolve']:checked").val();  //31
var CriminalCases1 = $("#criminalcasestext").val(); //31a
var DepartmentalEnquiry = $("input[name='departmentalenquiry']:checked").val();  //32
var Deptenq = $("#deptenx").val(); //32a
var ConvictedinaCriminal = $("input[name='criminalcasesconvicted']:checked").val(); //33
var CriminalCases2 = $("#yescriminalcase").val(); //33a